version: '2'

services:
  web04-backend:
    image: 'web04:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web04
    ports:
      - "2346:2346"
    depends_on:
      - service-db

  service-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
        - "15432:5432"
    volumes:
        - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data: